name: "Update content every day"
on:
  schedule:
    - cron: "0 1 * * *"
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v2.3.1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: recursive

      - run: ./.github/scripts/decrypt-team-provider.sh
        env:
          PASS_PHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}

      - name: Configure amplify
        uses: ambientlight/amplify-cli-action@0.2.1
        with:
          project_dir: ./site
          amplify_command: configure
          amplify_env: production
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-central-1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@hello-nyxo"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        working-directory: site
        run: |
          yarn install --frozen-lockfile --non-interactive
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        working-directory: site
        run: |
          yarn build
        env:
          GATSBY_TELEMETRY_DISABLED: 1
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
          ACCOUNT_KEY: ${{ secrets.ACCOUNT_KEY }}
          VIEW_ID: ${{ secrets.VIEW_ID }}

      - uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=public --prod
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'

      - name: Spam Slack
        if: always()
        uses: adamkdean/simple-slack-notify@1.0.4
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          channel: "#development"
          username: "coaching.nyxo.app"
          status: ${{ job.status }}
          success_text: "New version (#${env.GITHUB_RUN_NUMBER}) of Nyxo theme completed successfully. Go to coaching.nyxo.app to see it in action"
          failure_text: "Deployment (#${env.GITHUB_RUN_NUMBER}) of Nyxo theme failed. Please go see what's wrong with this build"
          cancelled_text: "Deployment (#${env.GITHUB_RUN_NUMBER}) was cancelled"
          fields: |
            [{ "title": "Host", "value": "${{ secrets.DEPLOY_HOST }}"},
            { "title": "Action URL", "value": "${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}/actions/runs/${env.GITHUB_RUN_ID}"}]
